apiVersion: v1
kind: Pod
metadata:
  name: probe-liveness-readiness-tcp
spec:
  containers:
  - name: probe-liveness-readiness-tcp
    image: nginx
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 60
